version: "3.3"
services:
    db:
        image: postgres
        container_name: db
        ports:
        - "5432:5432"
        environment:
          - POSTGRES_PASSWORD=${DB_PASSWORD}
          - POSTGRES_USER=${DB_USERNAME}
          - POSTGRES_DB=${DB_USERNAME}
        volumes:
          - ./backend/docker/sql:/docker-entrypoint-initdb.d
        networks:
            - lan
    wildfly:
        build: ./backend/docker
        container_name: wildfly
        depends_on:
            - db
        ports:
            - "8080:8080"
            - "9990:9990"
            - "58787:8787"
        environment:
            JBOSS_HOME: /opt/jboss/wildfly
            JDBC_CONNECTION_URL: ${JDBC_CONNECTION_URL}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        volumes:
          - ./backend/project/ear-me-all-ear/target/deployment:/opt/jboss/wildfly/standalone/deployments/
        networks:
            - lan
    frontend:
        build: ./frontend
        container_name: frontend
        depends_on:
            - wildfly  
        ports:
          - "80:3000"
        volumes:
          - ./frontend:/home/eatmeall/frontend
          - /home/eatmeall/frontend/node_modules/
        environment:
          - CHOKIDAR_USEPOLLING=true npm start
          - NODE_ENV=development
        networks:
          - lan       
networks:
    lan:
